### ISSUE TITLE
.isConnected() always returns true. .logout() does not remove the address from provider

### ISSUE THREAD

**Issue by bogdanIuga** [ElrondNetwork/elrond-sdk-erdjs-extension-provider#4]
Hello,

I think there's an issue with the .isConnected() function. It always returns true, giving the fact that you check if it's truthy but in the constructor you're initalizing the address as empty.

Also, the .logout() method shouldn't remove the address from the provider.account?
I've added this function on your example:
![image](https://user-images.githubusercontent.com/26706013/169891502-15071433-220e-4ad0-928c-2a56b1abfd87.png)

But the address is still on the provider, after clicking on "Logout". The .isConnected() method returns true
![image](https://user-images.githubusercontent.com/26706013/169891526-2d1413ec-674c-4507-a238-b66d9b02e210.png)

The function is added in the app.js from out-examples.

Hopefully I'm not doing anything wrong :).
Using Angular
![image](https://user-images.githubusercontent.com/26706013/169891963-002e0ea1-c588-493b-b2e6-03f980cb3904.png)

**Comment by juliancwirko** [comment]
I missed the issue and created a PR, but just found the same: https://github.com/ElrondNetwork/elrond-sdk-erdjs-extension-provider/pull/6

it is also not concise across the providers, it would be good to have the same login for isConnected, for example, wallet connect provider returns the isInitialized: https://github.com/ElrondNetwork/elrond-sdk-erdjs-wallet-connect-provider/issues/8

**Comment by andreibancioiu** [comment]
@bogdanIuga, @juliancwirko, thank you for raising the issue. 

@juliancwirko, thank you for the fix :pray:. 

It has been released a few moments ago: https://github.com/ElrondNetwork/elrond-sdk-erdjs-extension-provider/releases/tag/v2.0.3

**Comment by andreibancioiu** [comment]
Regarding the uniformity of function names / interfaces across different providers - indeed, there are discrepancies between them at this moment.

However, the `initialized` state (kept in a private variable for the extension provider) and the `connected` state have different semantics in the context of the extension provider, and we'd like to keep them explicitly separated, at least for the moment - this could be improved in the future.

All right to close this issue? 

Thanks again :pray:
